repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: name-tests-test
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
    -   id: check-merge-conflict
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        additional_dependencies:
            -   flake8-typing-imports==1.16.0
            -   flake8-comprehensions==3.16.0
            -   flake8-noqa==1.4.0
            -   flake8-timeout==0.3.0
            -   flake8-ban-utcnow==0.2.0
        args: [
            "--min-python-version=3.12",
            "--max-line-length=88",
        ]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
-   repo: https://github.com/jkittner/double-indent
    rev: 0.1.5
    hooks:
    -    id: double-indent
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: [--py39-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    -   id: mypy
