[project]
name = "t"
description = "test"
version = "0.1.0"

[tool.coverage.report]
fail_under = 100

[tool.coverage.run]
plugins = ["covdefaults"]
parallel = true
source = ["t", "tests"]

[tool.coverage.paths]
wat = ["src", "*/site-packages"]
